#!/usr/bin/env python
import sys
import os

cmd = ['qemu-system-arm',
       '-machine', 'lm3s811evb',
       '-kernel', sys.argv[1],
       '-nographic',
       '-semihosting',
       '-d', 'guest_errors']

for arg in sys.argv[1:]:
    cmd += ['-semihosting-config', 'arg=' + arg]

os.execlp('qemu-system-arm', *cmd)

